### ISSUE TITLE
Replace the `typeof` solution

### ISSUE THREAD

**Issue by thequickf** [thequickf/graph#7]
Implementing a traits logic through the Graph class customization dependent on static checks comes out to be not the best way to go.
We should think about alternatives.

**Comment by isnullxbh** [comment]
Why don't you use `decltype`? It is a standard thing, unlike `typeof`.

**Comment by thequickf** [comment]
> Why don't you use `decltype`? It is a standard thing, unlike `typeof`.

I wasn't able to make `decltype` work (I guess template woodoo messed it up). I would appreciate a PR with working `decltype` replacement.
